### ISSUE TITLE
NoSuchElementException when retrieving fcr:metadata 

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#1012]
The file http://127.0.0.1:8986/rest/test/3b/59/18/56/3b5918567/files/83edf10d-f403-4cdf-9894-f3dbdde0b27f downloads fine, but checking its `fcr:metadata` throws a stack trace:

This is on Fedora 4.5.0. And it is reproducable in a branch of curation_concerns: https://github.com/projecthydra-labs/curation_concerns/pull/693

```
HTTP HEAD (14.65ms)  http://127.0.0.1:8986/rest/test/3b/59/18/56/3b5918567/files/83edf10d-f403-4cdf-9894-f3dbdde0b27f/fcr:metadata
Response status  Net::HTTPOK (200)
HTTP GET (19.44ms)  http://127.0.0.1:8986/rest/test/3b/59/18/56/3b5918567/files/83edf10d-f403-4cdf-9894-f3dbdde0b27f/fcr:metadata
Response status  Net::HTTPInternalServerError (500)
Response body  java.util.NoSuchElementException
	at com.google.common.collect.Iterators$1.next(Iterators.java:80)
	at org.fcrepo.kernel.modeshape.rdf.impl.mappings.PropertyValueIterator.computeNext(PropertyValueIterator.java:68)
	at org.fcrepo.kernel.modeshape.rdf.impl.mappings.PropertyValueIterator.computeNext(PropertyValueIterator.java:35)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.google.common.collect.ForwardingIterator.hasNext(ForwardingIterator.java:43)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at org.openrdf.rio.Rio.write(Rio.java:564)
	at org.fcrepo.http.commons.responses.RdfStreamStreamingOutput.write(RdfStreamStreamingOutput.java:136)
	at org.fcrepo.http.commons.responses.RdfStreamStreamingOutput.write(RdfStreamStreamingOutput.java:111)
	at org.fcrepo.http.commons.responses.RdfStreamProvider.writeTo(RdfStreamProvider.java:109)
	at org.fcrepo.http.commons.responses.RdfStreamProvider.writeTo(RdfStreamProvider.java:60)
	at org.glassfish.jersey.message.internal.WriterI

<some data truncated>

sfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by escowles** [comment]
Running the CurationConcerns tests with fcrepo 4.5.0 were failing.  Running the same tests against a current master branch build of fcrepo4 resolved the issue and the tests passed.  So this issue looks resolved in master, and will be included in the upcoming 4.5.1 release.
