### ISSUE TITLE
java.lang.IllegalArgumentException for ID ".../Kyntschew:%20Galaktisieren%20der%20Leere" 

### ISSUE THREAD

**Issue by dla-kramski** [fcrepo4/fcrepo4#1562]
Just playing around with Release: 5.1.0 | Build #7bb1f9fa (2019-07-27, java-12-openjdk on Arch Linux), I was able to add a basic container named "http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere" (note the colon). 

However, it can not be navigated to using the GUI. GET or DELETE via curl also fail with:

```
java.lang.IllegalArgumentException: The localName argument may not be null or zero-length
	at org.modeshape.common.util.CheckArg.isNotZeroLength(CheckArg.java:360)
	at org.modeshape.common.util.CheckArg.isNotEmpty(CheckArg.java:373)
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:175)
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:168)
	at org.modeshape.jcr.cache.document.DocumentTranslator.getProperties(DocumentTranslator.java:245)
	at org.modeshape.jcr.cache.document.LazyCachedNode.getProperties(LazyCachedNode.java:425)
	at org.modeshape.jcr.AbstractJcrNode.getProperties(AbstractJcrNode.java:2074)
	at org.fcrepo.kernel.modeshape.rdf.impl.PropertiesRdfContext.triplesFromProperties(PropertiesRdfContext.java:75)
	at org.fcrepo.kernel.modeshape.rdf.impl.PropertiesRdfContext.<init>(PropertiesRdfContext.java:65)
	at org.fcrepo.kernel.modeshape.FedoraResourceImpl.lambda$null$16(FedoraResourceImpl.java:194)
	at org.fcrepo.kernel.modeshape.utils.UncheckedFunction.apply(UncheckedFunction.java:37)
	at org.fcrepo.kernel.modeshape.FedoraResourceImpl.lambda$getTriples$57(FedoraResourceImpl.java:967)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at org.fcrepo.kernel.modeshape.FedoraResourceImpl.getTriples(FedoraResourceImpl.java:968)
	at org.fcrepo.kernel.modeshape.FedoraResourceImpl.getTriples(FedoraResourceImpl.java:958)
	at org.fcrepo.http.api.ContentExposingResource.getTriples(ContentExposingResource.java:458)
	at org.fcrepo.http.api.ContentExposingResource.getResourceTriples(ContentExposingResource.java:343)
	at org.fcrepo.http.api.ContentExposingResource.getContent(ContentExposingResource.java:276)
	at org.fcrepo.http.api.FedoraLdp.getResource(FedoraLdp.java:297)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:840)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.base/java.lang.Thread.run(Thread.java:835)

```

**Comment by whikloj** [comment]
Hi @dla-kramski,

Is this being run in Tomcat and if so which version? I did a quick test against the internal jetty server and could not duplicate the issue so I am wondering if Tomcat is doing some encoding we are not expecting.

```
> curl -i -ufedoraAdmin:fedoraAdmin -XPUT "http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere"
HTTP/1.1 201 Created
Date: Thu, 03 Oct 2019 12:54:41 GMT
Set-Cookie: JSESSIONID=1cxekfi50782f1g8oo6f59dyw9;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Wed, 02-Oct-2019 12:54:41 GMT
ETag: W/"1797fdbb27b8da938acca6c22e3de4b4295f7aba"
X-State-Token: 1797fdbb27b8da938acca6c22e3de4b4295f7aba
Last-Modified: Thu, 03 Oct 2019 12:54:41 GMT
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere>; rel="timegate"
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere>; rel="original"
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere/fcr:versions>; rel="timemap"
Link: <http://mementoweb.org/ns#OriginalResource>; rel="type"
Link: <http://mementoweb.org/ns#TimeGate>; rel="type"
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere/fcr:acl>; rel="acl"
Location: http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere
Content-Type: text/plain
Content-Length: 94
Server: Jetty(9.3.25.v20180904)

http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere%

[/Users/whikloj] 
> curl -i -ufedoraAdmin:fedoraAdmin -G "http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere"
HTTP/1.1 200 OK
Date: Thu, 03 Oct 2019 12:55:03 GMT
Set-Cookie: JSESSIONID=hu610yjsxcq9uj40ikj2q3ph;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Wed, 02-Oct-2019 12:55:03 GMT
ETag: W/"1797fdbb27b8da938acca6c22e3de4b4295f7aba"
X-State-Token: 1797fdbb27b8da938acca6c22e3de4b4295f7aba
Last-Modified: Thu, 03 Oct 2019 12:54:41 GMT
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere>; rel="timegate"
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere>; rel="original"
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere/fcr:versions>; rel="timemap"
Link: <http://mementoweb.org/ns#OriginalResource>; rel="type"
Link: <http://mementoweb.org/ns#TimeGate>; rel="type"
Accept-External-Content-Handling: copy,redirect,proxy
Accept-Patch: application/sparql-update
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json
Allow: MOVE,COPY,DELETE,POST,HEAD,GET,PUT,PATCH,OPTIONS
Link: <http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere/fcr:acl>; rel="acl"
Preference-Applied: return=representation
Vary: Prefer
Vary: Accept
Vary: Range
Vary: Accept-Encoding
Vary: Accept-Language
Vary: Accept-Datetime
Content-Type: text/turtle;charset=utf-8
Content-Length: 820
Server: Jetty(9.3.25.v20180904)

@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .

<http://localhost:8080/rest/SDC4Lit/Try/Objects/Global/Kyntschew:%20Galaktisieren%20der%20Leere>
        rdf:type               fedora:Container ;
        rdf:type               fedora:Resource ;
        rdf:type               ldp:BasicContainer ;
        fedora:lastModifiedBy  "fedoraAdmin" ;
        fedora:createdBy       "fedoraAdmin" ;
        fedora:created         "2019-10-03T12:54:41.818Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2019-10-03T12:54:41.818Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container .
```

Also we use https://jira.duraspace.org/ to track our issues, would you be able to create an account and open a ticket there? You can tag me on it so I won't lose you.

**Comment by dla-kramski** [comment]
I was using the standalone version with jetty.

I went on with an older backup, and unfortunately, I can now reproduce the issue neither.

If it ever occurs again, I will open a ticket on https://jira.duraspace.org/. Thanks for looking into this.

Heinz
