### ISSUE TITLE
StackOverflowError when updating the node types

### ISSUE THREAD

**Issue by ds-jool** [fcrepo4/fcrepo4#424]
When updating the node types via the HTML interface (/rest/fcr:nodetypes) I've encountered a bug (in fcrepo-4.0.0-beta-01).

First thing I did was update the node types with the following CND:
```
<skt = 'http://jool.nl/test'>
[skt:TestItem]
 - skt:firstProperty 
 - skt:secondProperty (string)
 - skt:thirdProperty (string) multiple
```
This went fine. However then I tried the update node types again, with the same CND except for a trailing slash in the namespace:
```
<skt = 'http://jool.nl/test/'>
[skt:TestItem]
 - skt:firstProperty 
 - skt:secondProperty (string)
 - skt:thirdProperty (string) multiple
```
Afterwards when retrieving the the node types via /rest/fcr:nodetypes, I am getting an error 500 caused by a StackOverflowError:
```
org.infinispan.CacheException: java.lang.StackOverflowError
	at org.infinispan.interceptors.InterceptorChain.invoke(InterceptorChain.java:351)
	at org.infinispan.CacheImpl.get(CacheImpl.java:391)
	at org.infinispan.CacheImpl.get(CacheImpl.java:383)
	at org.infinispan.schematic.internal.CacheSchematicDb.get(CacheSchematicDb.java:235)
	at org.modeshape.jcr.cache.document.LocalDocumentStore.get(LocalDocumentStore.java:78)
	at org.modeshape.jcr.cache.document.WorkspaceCache.documentFor(WorkspaceCache.java:164)
	at org.modeshape.jcr.cache.document.WorkspaceCache.documentFor(WorkspaceCache.java:183)
	at org.modeshape.jcr.cache.document.WorkspaceCache.getNode(WorkspaceCache.java:215)
	at org.modeshape.jcr.cache.document.AbstractSessionCache.getNode(AbstractSessionCache.java:237)
	at org.modeshape.jcr.cache.document.WritableSessionCache.getNode(WritableSessionCache.java:169)
	at org.modeshape.jcr.SystemContent.readNamespacePrefix(SystemContent.java:760)
	at org.modeshape.jcr.SystemNamespaceRegistry.getPrefixForNamespaceUri(SystemNamespaceRegistry.java:123)
	at org.modeshape.jcr.value.basic.BasicName.getString(BasicName.java:113)
	at org.modeshape.jcr.NodeTypeSchemata.addAllNodesTable(NodeTypeSchemata.java:195)
	at org.modeshape.jcr.NodeTypeSchemata.<init>(NodeTypeSchemata.java:138)
	at org.modeshape.jcr.RepositoryNodeTypeManager.getRepositorySchemata(RepositoryNodeTypeManager.java:293)
	at org.modeshape.jcr.JcrRepository$RepositoryMonitorFactory.indexingMonitor(JcrRepository.java:1913)
	at org.modeshape.jcr.JcrRepository$RepositoryMonitorFactory.createMonitor(JcrRepository.java:1908)
	at org.modeshape.jcr.txn.Transactions.newMonitor(Transactions.java:243)
	at org.modeshape.jcr.txn.SynchronizedTransactions$SynchronizedTransaction.<init>(SynchronizedTransactions.java:165)
	at org.modeshape.jcr.txn.SynchronizedTransactions.begin(SynchronizedTransactions.java:77)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:443)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:420)
	at org.modeshape.jcr.SystemContent.save(SystemContent.java:110)
	at org.modeshape.jcr.SystemNamespaceRegistry.getPrefixForNamespaceUri(SystemNamespaceRegistry.java:125)
	at org.modeshape.jcr.value.basic.BasicName.getString(BasicName.java:113)
	at org.modeshape.jcr.NodeTypeSchemata.addAllNodesTable(NodeTypeSchemata.java:195)
	at org.modeshape.jcr.NodeTypeSchemata.<init>(NodeTypeSchemata.java:138)
	at org.modeshape.jcr.RepositoryNodeTypeManager.getRepositorySchemata(RepositoryNodeTypeManager.java:293)
	at org.modeshape.jcr.JcrRepository$RepositoryMonitorFactory.indexingMonitor(JcrRepository.java:1913)
	at org.modeshape.jcr.JcrRepository$RepositoryMonitorFactory.createMonitor(JcrRepository.java:1908)
	at org.modeshape.jcr.txn.Transactions.newMonitor(Transactions.java:243)
	at org.modeshape.jcr.txn.SynchronizedTransactions$SynchronizedTransaction.<init>(SynchronizedTransactions.java:165)
	at org.modeshape.jcr.txn.SynchronizedTransactions.begin(SynchronizedTransactions.java:77)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:443)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:420)
	at org.modeshape.jcr.SystemContent.save(SystemContent.java:110)
	at org.modeshape.jcr.SystemNamespaceRegistry.getPrefixForNamespaceUri(SystemNamespaceRegistry.java:125)
	at org.modeshape.jcr.value.basic.BasicName.getString(BasicName.java:113)
... (and so on; the last 13 lines keep repeating in the stack trace)
```
I continue to receive this error whenever I try to access the node types.

**Comment by awoods** [comment]
The REST-API and related HTML UI for updating node types have been dropped from the Fedora 4 feature set.
This this issue is OBE.
