### ISSUE TITLE
IOException: Response header too large using HTTP PUT on fcr:metadata

### ISSUE THREAD

**Issue by adolski** [fcrepo4/fcrepo4#815]
I can make Fedora 4.2 emit an IOException by attempting to PUT to a binary node's fcr:metadata, but only when the binary node is inside a container (apparently). To reproduce:

1. Create a binary node inside a container

2. `curl -X PUT -H "Content-Type: text/turtle" --data-binary "@test.rdf" "[node URL]/fcr:metadata"`

test.rdf:

    <> <http://example.org/test> <http://example.org/test2> .

Result is a 500 Internal Server Error:

INFO 12:19:44.124 (FedoraLdp) PUT resource '8a/51/7f/89/8a517f89-5b2b-43b6-8d7d-185125205131/d4/ed/92/09/d4ed9209-27fd-4783-a3ca-007181623910/69/73/2f/84/69732f84-7a2c-46a4-aae3-1515ffd81f02/fcr:metadata'
2015-06-15 09:52:05.969:WARN:oejs.HttpChannel:qtp1213415012-13: Commit failed
java.io.IOException: Response header too large
	at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:400)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:622)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:462)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:763)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:378)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:298)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:307)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:261)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:276)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:834)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:412)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:691)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:377)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:420)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at org.eclipse.jetty.http.HttpGenerator.putSanitisedValue(HttpGenerator.java:1057)
	at org.eclipse.jetty.http.HttpGenerator.putTo(HttpGenerator.java:1079)
	at org.eclipse.jetty.http.HttpGenerator.generateHeaders(HttpGenerator.java:703)
	at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:385)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:622)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:462)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:763)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:378)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:298)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:307)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:261)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:276)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:834)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:412)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:691)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:377)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:420)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by awoods** [comment]
I am able to see a large "Link; rel=constrainedBy" header, but do not get any error. It is easy to imagine that the max size of response headers depends on client configuration.
In any case, F4's handling of "Link: rel=constrainedBy" is being improved with:
https://jira.duraspace.org/browse/FCREPO-1418

Once the above ticket is resolved (this week?) it would be ideal if you could verify this error has gone away.

**Comment by acoburn** [comment]
This issue was resolved via https://github.com/fcrepo4/fcrepo4/commit/447e56a9546900f62a2f1ad7a75077280072e773
