### ISSUE TITLE
 javax.jcr.ItemExistsException returns a 500 and stack trace

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#957]
It should be caught and a 4xx should be returned instead.

```
    STATUS: 500 javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}42" in workspace "default"
    at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
    at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:541)
    at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:614)
    at org.modeshape.jcr.JcrSession.save(JcrSession.java:1166)
    at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:301)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java...
```

I think this occurs when two threads simultaneously try to create the same resource at the same time. Reported by @ojlyytinen here: https://github.com/projecthydra/sufia/issues/1362

**Comment by awoods** [comment]
Tracking with: https://jira.duraspace.org/browse/FCREPO-1872
..although reproducing the concurrent error has proven to be challenging. If you have a curl script, that would be helpful.

**Comment by awoods** [comment]
Which version of Fedora was used?

**Comment by ojlyytinen** [comment]
We have Fedora 4.1 on the server where we encountered this. We have a Sufia based Hydra setup and use Fedora through that but I think essentially what causes it is sending two requests at the same time to create a resource with the same path twice. Our server had a fairly high cpu load at the time (for unrelated reasons) which may have made it more susceptible to concurrency issues.

**Comment by acoburn** [comment]
Closing this issue as it is being tracked in Jira as https://jira.duraspace.org/browse/FCREPO-2086 and there is already a corresponding pull request.
